#!/usr/bin/env nextflow
/*
========================================================================================
                         nf-core/resolvinf
========================================================================================
 nf-core/resolvinf Analysis Pipeline.
 #### Homepage / Documentation
 https://github.com/nf-core/resolvinf
----------------------------------------------------------------------------------------
*/

nextflow.enable.dsl = 2

/*
 * DEFAULT PARAMETERS
 */
params.help = false
params.input = null
params.outdir = './results'
params.annotation_label = 'cell_type'
params.marker_genes = null
params.max_epochs = 100
params.num_samples = 20
params.num_gpus = 0
params.da_comparisons = null
params.scviva_max_epochs = 100
params.scviva_comparisons = null
params.email = null
params.email_on_fail = null
params.max_multiqc_email_size = '25MB'
params.name = false
params.awsqueue = null
params.awsregion = null
params.awscli = null
params.tracedir = "${params.outdir}/pipeline_info"
params.max_memory = '128.GB'
params.max_cpus = 16
params.max_time = '240.h'
params.config_profile_description = null
params.config_profile_contact = null
params.config_profile_url = null
params.hostnames = false

def helpMessage() {
    log.info"""

    Usage:

    The typical command for running the pipeline is as follows:

    nextflow run nf-core/resolvinf --input samplesheet.csv -profile docker

    Mandatory arguments:
      --input [file]                  Path to comma-separated file containing information about the samples (must be surrounded with quotes)
      -profile [str]                  Configuration profile to use. Can use multiple (comma separated)
                                      Available: conda, docker, singularity, test, awsbatch, <institute> and more

    ResolVI options:
      --annotation_label [str]        Column name to use for cell type annotation (default: 'cell_type')
      --marker_genes [file]           Path to file containing marker genes (one per line) or comma-separated list
      --max_epochs [int]              Maximum training epochs (default: 100)
      --num_samples [int]             Number of posterior samples (default: 20)
      --num_gpus [int]                Number of GPUs for model training. 0 for CPU, -1 for all available (default: auto-detect)
      --da_comparisons [file]         JSON or CSV file specifying differential abundance comparisons

    scVIVA options:
      --scviva_max_epochs [int]       Maximum training epochs for scVIVA (default: 100)
      --scviva_comparisons [file]     JSON or CSV file specifying scVIVA niche-aware DE comparisons

    Other options:
      --outdir [file]                 The output directory where the results will be saved (default: './results')
      --email [email]                 Set this parameter to your e-mail address to get a summary e-mail with details of the run sent to you when the workflow exits
      --email_on_fail [email]         Same as --email, except only send mail if the workflow is not successful
      --max_multiqc_email_size [str]  Threshold size for MultiQC report to be attached in notification email. If file generated by pipeline exceeds the threshold, it will not be attached (Default: 25MB)
      -name [str]                     Name for the pipeline run. If not specified, Nextflow will automatically generate a random mnemonic

    AWSBatch options:
      --awsqueue [str]                The AWSBatch JobQueue that needs to be set when running on AWSBatch
      --awsregion [str]               The AWS Region for your AWS Batch job to run on
      --awscli [str]                  Path to the AWS CLI tool
    """.stripIndent()
}

// Show help message
if (params.help) {
    helpMessage()
    exit 0
}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT MODULES/SUBWORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

include { RESOLVI_PREPROCESS } from './modules/local/resolvi_preprocess'
include { RESOLVI_TRAIN } from './modules/local/resolvi_train'
include { RESOLVI_ANALYZE } from './modules/local/resolvi_analyze'
include { RESOLVI_VISUALIZE } from './modules/local/resolvi_visualize'
include { SCVIVA_TRAIN } from './modules/local/scviva_train'
include { SCVIVA_ANALYZE } from './modules/local/scviva_analyze'

/*
 * SET UP CONFIGURATION VARIABLES
 */

// Has the run name been specified by the user?
//  this has the bonus effect of catching both -name and --name
custom_runName = params.name
if (!(workflow.runName ==~ /[a-z]+_[a-z]+/)) {
    custom_runName = workflow.runName
}

if (workflow.profile.contains('awsbatch')) {
    // AWSBatch sanity checking
    if (!params.awsqueue || !params.awsregion) exit 1, "Specify correct --awsqueue and --awsregion parameters on AWSBatch!"
    // Check outdir paths to be S3 buckets if running on AWSBatch
    // related: https://github.com/nextflow-io/nextflow/issues/813
    if (!params.outdir.startsWith('s3:')) exit 1, "Outdir not on S3 - specify S3 Bucket to run on AWSBatch!"
    // Prevent trace files to be stored on S3 since S3 does not support rolling files.
    if (params.tracedir.startsWith('s3:')) exit 1, "Specify a local tracedir or run without trace! S3 cannot be used for tracefiles."
}

// Stage config files
ch_output_docs = file("$baseDir/docs/output.md", checkIfExists: false)

/*
 * Create a channel for input spatialdata files
 */
if (!params.input) {
    exit 1, "Input samplesheet not specified!"
}

// Process marker genes parameter
ch_marker_genes = Channel.empty()
if (params.marker_genes) {
    if (params.marker_genes instanceof String && params.marker_genes.endsWith('.txt')) {
        // If it's a file path
        ch_marker_genes = Channel.fromPath(params.marker_genes, checkIfExists: true)
    } else {
        // If it's a list or comma-separated string
        def genes = params.marker_genes instanceof List ? params.marker_genes : params.marker_genes.split(',')
        ch_marker_genes = Channel.of(genes)
    }
}

// Header log info
log.info """
=======================================================
                    nf-core/resolvinf
=======================================================
""".stripIndent()

def summary = [:]
if (workflow.revision) summary['Pipeline Release'] = workflow.revision
summary['Run Name']         = custom_runName ?: workflow.runName
summary['Input']            = params.input
summary['Annotation Label'] = params.annotation_label ?: 'cell_type'
summary['Marker Genes']     = params.marker_genes ? (params.marker_genes instanceof List ? params.marker_genes.size() + " genes" : params.marker_genes) : 'Default set'
summary['Max Epochs']       = params.max_epochs
summary['Num Samples']      = params.num_samples
summary['Num GPUs']         = params.num_gpus ?: 'Auto-detect'
summary['DA Comparisons']   = params.da_comparisons ?: 'Default pairwise'
summary['scVIVA Max Epochs'] = params.scviva_max_epochs
summary['scVIVA Comparisons'] = params.scviva_comparisons ?: 'Default pairwise'
summary['Max Resources']    = "$params.max_memory memory, $params.max_cpus cpus, $params.max_time time per job"
if (workflow.containerEngine) summary['Container'] = "$workflow.containerEngine - $workflow.container"
summary['Output dir']       = params.outdir
summary['Launch dir']       = workflow.launchDir
summary['Working dir']      = workflow.workDir
summary['Script dir']       = workflow.projectDir
summary['User']             = workflow.userName
if (workflow.profile.contains('awsbatch')) {
    summary['AWS Region']   = params.awsregion
    summary['AWS Queue']    = params.awsqueue
    summary['AWS CLI']      = params.awscli
}
summary['Config Profile'] = workflow.profile
if (params.config_profile_description) summary['Config Description'] = params.config_profile_description
if (params.config_profile_contact)     summary['Config Contact']     = params.config_profile_contact
if (params.config_profile_url)         summary['Config URL']         = params.config_profile_url
if (params.email || params.email_on_fail) {
    summary['E-mail Address']    = params.email
    summary['E-mail on failure'] = params.email_on_fail
    summary['MultiQC maxsize']   = params.max_multiqc_email_size
}
log.info summary.collect { k,v -> "${k.padRight(18)}: $v" }.join("\n")
log.info "-\033[2m--------------------------------------------------\033[0m-"

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

workflow {
    // Create input channel from samplesheet
    ch_input = Channel
        .fromPath(params.input)
        .splitCsv(header: true)
        .map { row ->
            def meta = [:]
            meta.id = row.sample_id
            meta.single_cell = true
            [meta, file(row.zarr_path, checkIfExists: true)]
        }

    ch_versions = Channel.empty()

    // MODULE: Run preprocessing
    RESOLVI_PREPROCESS (
        ch_input,
        params.annotation_label
    )
    ch_versions = ch_versions.mix(RESOLVI_PREPROCESS.out.versions.first())

    // MODULE: Train ResolVI model
    RESOLVI_TRAIN (
        RESOLVI_PREPROCESS.out.adata,
        params.annotation_label,
        params.max_epochs,
        params.num_samples,
        params.num_gpus
    )
    ch_versions = ch_versions.mix(RESOLVI_TRAIN.out.versions.first())

    // Combine model and adata for RESOLVI_ANALYZE
    ch_resolvi_combined = RESOLVI_TRAIN.out.model
        .join(RESOLVI_TRAIN.out.adata, by: 0)
        .map { meta, model_dir, adata -> [meta, model_dir, adata] }

    // Branch 1: ResolVI Analysis
    RESOLVI_ANALYZE (
        ch_resolvi_combined,
        params.da_comparisons ?: "default_pairwise"
    )
    ch_versions = ch_versions.mix(RESOLVI_ANALYZE.out.versions.first())

    // Branch 2: scVIVA Training
    SCVIVA_TRAIN (
        RESOLVI_TRAIN.out.model,
        RESOLVI_TRAIN.out.adata,
        params.scviva_max_epochs,
        params.num_gpus
    )
    ch_versions = ch_versions.mix(SCVIVA_TRAIN.out.versions.first())

    // Branch 3: scVIVA Analysis
    SCVIVA_ANALYZE (
        SCVIVA_TRAIN.out.model_dir,
        SCVIVA_TRAIN.out.adata_trained,
        params.scviva_comparisons ?: "default_pairwise"
    )
    ch_versions = ch_versions.mix(SCVIVA_ANALYZE.out.versions.first())

    // Branch 4: ResolVI Visualization
    RESOLVI_VISUALIZE (
        RESOLVI_TRAIN.out.adata,
        params.marker_genes
    )
    ch_versions = ch_versions.mix(RESOLVI_VISUALIZE.out.versions.first())

    emit:
    versions = ch_versions
}

/*
 * Parse software version numbers
 */
process get_software_versions {
    publishDir "${params.outdir}/pipeline_info", mode: 'copy',
        saveAs: { filename ->
                      if (filename.indexOf(".csv") > 0) filename
                      else null
                }

    output:
    path 'software_versions_mqc.yaml', emit: yaml
    path "software_versions.csv"

    script:
    """
    echo $workflow.manifest.version > v_pipeline.txt
    echo $workflow.nextflow.version > v_nextflow.txt
    python --version > v_python.txt
    pip list | grep -E "(scanpy|scvi-tools|spatialdata)" > v_spatial_tools.txt || echo "No spatial tools found" > v_spatial_tools.txt

    # Create a simple software versions file
    cat > software_versions_mqc.yaml << EOF
    id: 'software_versions'
    section_name: 'Software Versions'
    section_href: 'https://github.com/nf-core/resolvinf'
    plot_type: 'html'
    description: 'are collected at run time from the software output.'
    data: |
        <dl class="dl-horizontal">
            <dt>Pipeline</dt><dd>v$workflow.manifest.version</dd>
            <dt>Nextflow</dt><dd>v$workflow.nextflow.version</dd>
        </dl>
    EOF

    # Create CSV file
    echo "Software,Version" > software_versions.csv
    echo "Pipeline,$workflow.manifest.version" >> software_versions.csv
    echo "Nextflow,$workflow.nextflow.version" >> software_versions.csv
    """
}

/*
 * Output Description HTML
 */
process output_documentation {
    publishDir "${params.outdir}/pipeline_info", mode: 'copy'

    input:
    path output_docs

    output:
    path "results_description.html"

    script:
    """
    # Create a simple HTML documentation
    cat > results_description.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>ResolVI-nf Results</title>
    </head>
    <body>
        <h1>ResolVI-nf Pipeline Results</h1>
        <p>This directory contains the results from the ResolVI-nf pipeline analysis.</p>
        <h2>Output Structure</h2>
        <ul>
            <li><strong>resolvi/</strong> - ResolVI model results and predictions</li>
            <li><strong>scviva/</strong> - scVIVA model results and niche-aware differential expression</li>
            <li><strong>pipeline_info/</strong> - Pipeline execution information and software versions</li>
        </ul>
    </body>
    </html>
    EOF
    """
}

/*
 * Completion e-mail notification
 */
workflow.onComplete {

    // Set up the e-mail variables
    def subject = "[nf-core/resolvinf] Successful: $workflow.runName"
    if (!workflow.success) {
        subject = "[nf-core/resolvinf] FAILED: $workflow.runName"
    }
    def email_fields = [:]
    email_fields['version'] = workflow.manifest.version
    email_fields['runName'] = custom_runName ?: workflow.runName
    email_fields['success'] = workflow.success
    email_fields['dateComplete'] = workflow.complete
    email_fields['duration'] = workflow.duration
    email_fields['exitStatus'] = workflow.exitStatus
    email_fields['errorMessage'] = (workflow.errorMessage ?: 'None')
    email_fields['errorReport'] = (workflow.errorReport ?: 'None')
    email_fields['commandLine'] = workflow.commandLine
    email_fields['projectDir'] = workflow.projectDir
    email_fields['summary'] = summary
    email_fields['summary']['Date Started'] = workflow.start
    email_fields['summary']['Date Completed'] = workflow.complete
    email_fields['summary']['Pipeline script file path'] = workflow.scriptFile
    email_fields['summary']['Pipeline script hash ID'] = workflow.scriptId
    if (workflow.repository) email_fields['summary']['Pipeline repository Git URL'] = workflow.repository
    if (workflow.commitId) email_fields['summary']['Pipeline repository Git Commit'] = workflow.commitId
    if (workflow.revision) email_fields['summary']['Pipeline Git branch/tag'] = workflow.revision
    if (workflow.container) email_fields['summary']['Docker image'] = workflow.container

    // On completion, print out the summary
    log.info "========================================="
    log.info "Pipeline completed at: $workflow.complete"
    log.info "Execution status: ${ workflow.success ? 'OK' : 'failed' }"
    log.info "========================================="
}

def nfcoreHeader() {
    // Log colors ANSI codes
    def c_black = params.monochrome_logs ? '' : "\033[0;30m";
    def c_blue = params.monochrome_logs ? '' : "\033[0;34m";
    def c_cyan = params.monochrome_logs ? '' : "\033[0;36m";
    def c_dim = params.monochrome_logs ? '' : "\033[2m";
    def c_green = params.monochrome_logs ? '' : "\033[0;32m";
    def c_purple = params.monochrome_logs ? '' : "\033[0;35m";
    def c_reset = params.monochrome_logs ? '' : "\033[0m";
    def c_white = params.monochrome_logs ? '' : "\033[0;37m";
    def c_yellow = params.monochrome_logs ? '' : "\033[0;33m";

    return """    -${c_dim}--------------------------------------------------${c_reset}-
                                            ${c_green},--.${c_black}/${c_green},-.${c_reset}
    ${c_blue}        ___     __   __   __   ___     ${c_green}/,-._.--~\'${c_reset}
    ${c_blue}  |\\ | |__  __ /  ` /  \\ |__) |__         ${c_yellow}}  {${c_reset}
    ${c_blue}  | \\| |       \\__, \\__/ |  \\ |___     ${c_green}\\`-._,-`-,${c_reset}
                                            ${c_green}`._,._,\'${c_reset}
    ${c_purple}  nf-core/resolvinf v${workflow.manifest.version}${c_reset}
    -${c_dim}--------------------------------------------------${c_reset}-
    """.stripIndent()
}

def checkHostname() {
    def c_reset = params.monochrome_logs ? '' : "\033[0m"
    def c_white = params.monochrome_logs ? '' : "\033[0;37m"
    def c_red = params.monochrome_logs ? '' : "\033[1;91m"
    def c_yellow_bold = params.monochrome_logs ? '' : "\033[1;93m"
    if (params.hostnames) {
        def hostname = "hostname".execute().text.trim()
        params.hostnames.each { prof, hnames ->
            hnames.each { hname ->
                if (hostname.contains(hname) && !workflow.profile.contains(prof)) {
                    log.error "====================================================\n" +
                            "  ${c_red}WARNING!${c_reset} You are running with `-profile $workflow.profile`\n" +
                            "  but your machine hostname is ${c_white}'$hostname'${c_reset}\n" +
                            "  ${c_yellow_bold}It's highly recommended that you use `-profile $prof${c_reset}`\n" +
                            "============================================================"
                }
            }
        }
    }
}
